import URDF_TEXT from "../public/urdf/SO101/so101_new_calib.urdf?raw";
import HULL from "./so101-hull.json";
import { parseURDF } from "./urdf.js";
import { mountSO101, setJoints } from "./so101.js";

/* =========================================================================
   The SO-101's physical extent, for collision checks.

   A kinematics-only copy of the arm (no meshes) plus, per moving link, the
   mesh points that are extreme in some direction (so101-hull.json,
   generated by scripts/build-so101-hull.mjs). The furthest the real body
   reaches along any direction is reached at one of those points.
   ========================================================================= */
let body = null;

function build() {
  const robot = parseURDF(URDF_TEXT, { label: "SO-101 URDF" });
  const { holder } = mountSO101(robot);
  const links = Object.entries(HULL.links).map(([name, pts]) => ({
    node: robot.links[name],
    pts: Float64Array.from(pts.flat())
  }));
  return { robot, holder, links };
}

/* The largest world x (sign = 1) or -x (sign = -1) that any part of the
   moving arm reaches at joints q, in the arm's own frame (pan axis at the
   origin). Only the x row of each link's world matrix is needed. */
export function bodyReach(q, sign) {
  body ??= build();
  setJoints(body.robot, q);
  body.holder.updateMatrixWorld(true);
  let worst = -Infinity;
  for (const { node, pts } of body.links) {
    const e = node.matrixWorld.elements;
    const a = e[0] * sign, b = e[4] * sign, c = e[8] * sign, d = e[12] * sign;
    for (let i = 0; i < pts.length; i += 3) {
      const x = a * pts[i] + b * pts[i + 1] + c * pts[i + 2] + d;
      if (x > worst) worst = x;
    }
  }
  return worst;
}
